# Generated by Django 5.1.2 on 2024-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dateofbirth', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('refno', models.IntegerField()),
            ],
        ),
    ]
